---
- name: Ansible k8s module example
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: demo-2 # defining the namespace
        api_version: v1
        kind: Namespace
        state: present    # State=present when you need to create new object

# Copying the Pod.yaml and deployment.yaml in the remote node which will be further used to create the pods and deployment in the kubernetes cluster

    - name: copying file with playbook
      become: true
      copy:
        src: pod.yaml
        dest: /tmp/pod.yaml

    - name: copying file with playbook
      become: true
      copy:
        src: deployment.yaml
        dest: /tmp/deployment.yaml

# Creating a Kubernetes pod in demo-2 using file stored locally

    - name: Create a pod
      k8s:
        state: present      # State=present when you need to create new object
        namespace: demo-2  # defining the namespace
        src: /tmp/pod.yaml

# Checking the a Kubernetes pods in the demo-2

    - name: Get an existing Pods in the kubernetes cluster
      k8s:
        api_version: v1
        kind: pod
        name: nginx
        namespace: demo-2  # defining the namespace
      register: web_service

# Creating a Kubernetes deployment in demo-2 using file stored locally

    - name: Create a deployment
      k8s:
        state: present            # State=present when you need to create new object
        namespace: demo-2  # defining the namespace
        src: /tmp/deployment.yaml  # Source file location
