---
apiVersion: v1        # It is of type String
kind: Pod             # It is of type String
Namespace: demo-2
metadata:             # It is of type Dictionary
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:                  # It is of type List and Array
  containers:
  - name: nginx
    image: nginx
