---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - identityserver.yaml
  - github.com/ansible/awx-operator/config/default?ref=0.21.0
  - awx-demo.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.21.0

patches:
- config.yaml

namespace: default